apiVersion: v1
kind: Secret
metadata:
  name: {{ include "n8n.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
type: Opaque
data:
  encryptionKey: {{ include "n8n.encryptionKey" . | b64enc | quote }}
---
{{- if and (ne .Values.database.type "sqlite") (or .Values.database.postgresql.password .Values.database.mysql.password .Values.database.mariadb.password) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "n8n.fullname" . }}-db-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if eq .Values.database.type "postgresdb" }}
  password: {{ .Values.database.postgresql.password | b64enc | quote }}
  {{- else if eq .Values.database.type "mysqldb" }}
  password: {{ .Values.database.mysql.password | b64enc | quote }}
  {{- else if eq .Values.database.type "mariadb" }}
  password: {{ .Values.database.mariadb.password | b64enc | quote }}
  {{- end }}
{{- end }}
---
{{- if and (eq .Values.executionMode "queue") .Values.queue.redis.external .Values.queue.redis.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "n8n.fullname" . }}-redis-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.queue.redis.password | b64enc | quote }}
{{- end }}