# n8n deployment in queue mode with Redis and PostgreSQL

replicaCount: 1
executionMode: queue

# Queue configuration with Redis
queue:
  workerCount: 3
  redis:
    deploy: true
    external: false
    persistence:
      enabled: true
      size: 2Gi

# PostgreSQL database configuration
database:
  type: postgresdb
  postgresql:
    deploy: true
    external: false
    database: n8n
    username: n8n
    password: "n8n-queue-password-456"
    persistence:
      enabled: true
      size: 20Gi

# Enable persistence for n8n data  
persistence:
  enabled: true
  size: 10Gi

# Resource configuration
resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 1000m
    memory: 2Gi

workerResources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

# n8n configuration
n8n:
  encryptionKey: "myQueueEncryptionKey789012345678"
  taskRunners:
    enabled: true
    python:
      enabled: true
    javascript:
      enabled: true
  executions:
    timeout: 7200
    concurrencyProduction: 50
    dataMaxAge: 168

# Service configuration
service:
  type: ClusterIP
  port: 80

# Enable ingress
ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: n8n-queue.local
      paths:
        - path: /
          pathType: Prefix

# Enable pod disruption budget
podDisruptionBudget:
  enabled: true
  minAvailable: 1